
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class jfrmRepaso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmRepaso.class.getName());

    /**
     * Creates new form jfrmRepaso
     */
    public jfrmRepaso() {
        initComponents();
        this.setSize(700,450);
        this.setLocationRelativeTo(null);
        this.setTitle("Repaso ");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jltsColores = new javax.swing.JList<>();
        jbtnAceptar = new javax.swing.JButton();
        JpanelColor = new javax.swing.JPanel();
        jlblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jltsColores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rojo", "Azul", "Amarillo", "Verde", "Negro" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jltsColores);

        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.addActionListener(this::jbtnAceptarActionPerformed);

        javax.swing.GroupLayout JpanelColorLayout = new javax.swing.GroupLayout(JpanelColor);
        JpanelColor.setLayout(JpanelColorLayout);
        JpanelColorLayout.setHorizontalGroup(
            JpanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        JpanelColorLayout.setVerticalGroup(
            JpanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(JpanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JpanelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptar)
                .addGap(35, 35, 35)
                .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        String color= jltsColores.getSelectedValue();
        if (color==null){
            JOptionPane.showMessageDialog(this, "Diga un color");
            return;
            
        }
        String mensaje ="Color seleccionado"+color;
        JOptionPane.showMessageDialog(this,mensaje);
        switch(color) {
            case "Rojo":
                  JpanelColor.setBackground(java.awt.Color.RED);
                    jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folderxd/mario.png")));
                    break;
                     case "Azul":
                      JpanelColor.setBackground(java.awt.Color.BLUE );
                    jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folderxd/sonic.png")));
                    break;
                     case "Verde":
                         JpanelColor.setBackground(java.awt.Color.GREEN);
                    jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folderxd/shrek.png")));
                    break;
                     case "Amarillo":
                         JpanelColor.setBackground(java.awt.Color.YELLOW);
                    jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folderxd/pikachu.png")));
                    break;
                     case "Negro":
                         JpanelColor.setBackground(java.awt.Color.BLACK);
                    jlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folderxd/amongus.png")));
                    break;
        }
        
        
        
           
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmRepaso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelColor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JList<String> jltsColores;
    // End of variables declaration//GEN-END:variables

    private void MessageDialog(jfrmRepaso aThis, String mensaje) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
